import "./globals.css";
import { Inter } from "next/font/google";
import CustomCursor from "./components/customCursor";
import Navbar from "./components/Navbar.jsx";
import Footer from "./components/Footer.jsx"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Raju",
  description: "Generated by create next app",

}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">

      <body className={`${inter.className} lg:cursor-none`}>
        <CustomCursor/>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
